name: 'Build Java Maven Action'
#
description:
runs:
  using: "composite"
  steps:
     - name: Checkout repository
       uses: actions/checkout@v2
       with:
         fetch-depth: '0'
         
     - name: Setup environment
       id: env
       shell: bash
       run: |
         echo "Setup environment"
         ./build-manifest.sh

     - name: Run the preprocess shell script
       if: hashFiles('build-preprocess.sh') != ''
       shell: bash
       run: |
         echo "Run the preprocess shell script"
         ./build-preprocess.sh

     # NOTE: The language dependent build actions are responsible for creating the release with the release artifacts
     - name: Java/Maven build
       if: hashFiles('pom.xml') != ''
       uses: ${{ github.repository_owner }}/build-java-maven-action@v1
       with:
         java_version: ${{ steps.env.outputs.JAVA_VERSION }}
         java_distribution: ${{ steps.env.outputs.JAVA_DISTRIBUTION }}

     - name: Java/Gradle build
       if: hashFiles('build.gradle') != ''
       uses: ${{ github.repository_owner }}/build-java-gradle-action@v1
       with:
         java_version: ${{ steps.env.outputs.JAVA_VERSION }}
         java_distribution: ${{ steps.env.outputs.JAVA_DISTRIBUTION }}

     - name: Golang build
       shell: bash
       run: |
         echo "Golang build"

     - name: Run the postprocess shell script
       if: hashFiles('build-postprocess.sh') != ''
       shell: bash
       run: | 
         echo "Run the postprocess shell script"
         ./build-postprocess.sh
